public class APIT07_Entitlement_Utilities {
    
  /*  @InvocableMethod
    public static list<string> createEntitlementName (List<Decimal> totalEntitlements){
        
        list<string> entName = new list<string>();
        string s = 'SLA' + string.valueOf((integer)totalEntitlements[0]).leftPad(3 , '0');
        entName.add(s);
        system.debug('ENTNAME:: '+s);
        return entName;
    }*/

}